name: Deploy

on:
  release:
    types:
      - published
    paths-ignore:
      - '*.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Publish to NPM
        if: github.event_name == 'release'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
